### ISSUE TITLE
Files load in seemingly random order

### ISSUE THREAD

**Issue by arkholt** [jllodra/cmod3#13]
When adding a number of files, either by drag and drop or by using the "Add File" dialog, they load into the playlist in what appears to me to be a random order. Normally, I'd assume they should load in some kind of alphabetical order, either by title or by file name, but this is not the case. I did notice that when adding the same files again after clearing the playlist, it adds them again in the same order as before. Is there an explanation for this?

**Comment by jllodra** [comment]
You are right, because the file (and metadata) loading is done asynchronously, the order of files will be appear randomised. I will take a look at the loading code and use another approach.

Thank you

**Comment by jllodra** [comment]
OK, I think I got it... Songs show sorted now.

![image](https://cloud.githubusercontent.com/assets/273590/18483195/69621714-79e3-11e6-9537-70aa83600832.png)

I will release a new version in a couple of days or maybe next weekend.

**Comment by jllodra** [comment]
This has been fixed in the latest minor release: 2.1.1

https://github.com/jllodra/cmod3/releases/tag/2.1.1

**Comment by arkholt** [comment]
In the latest version, 2.2.1, while the filenames do now appear, it appears that the files are not sorting properly, the same as before. I didn't mention anything about it in 2.1.1, since it appears from your screenshot that the files are sorted by filename, and I thought that maybe if the filename did not appear it's possible that it then wasn't sorting. However, now in 2.2.1 the sorting problem has returned. Should this issue be reopened?

**Comment by jllodra** [comment]
Reopening...

**Comment by jllodra** [comment]
I am uploading a new version, 2,2.2.
I was only sorting files when folders were dropped, not when individual files were dropped. I have corrected this, it should work now. I am not closing the issue until you test this.
Thank you.

**Comment by arkholt** [comment]
Files are now sorted properly when dragging and dropping a folder as well as dragging and dropping files. However, files do not sort properly when clicking the "Add Files" button and selecting them in the dialog.

**Comment by jllodra** [comment]
You are right, thank you, I never use the "Add files" button so I didn't notice. 2.2.3 will be available in a few minutes.

**Comment by arkholt** [comment]
In 2.2.3, file sorting does appear to work with the "Add Files" button, when dragging and dropping files, and when dragging and dropping folders.
