### ISSUE TITLE
Filename not being loaded when files are added

### ISSUE THREAD

**Issue by arkholt** [jllodra/cmod3#24]
In the 2.1.1 release, on my Mac, when I add files either by clicking the button and selecting them through the dialog or by drag and drop, the song name will show up in the "SONG" column, but the file name will not appear in the "FILENAME" column. The list number and time will also be displayed. It's just the file name that is missing.

**Comment by jllodra** [comment]
@arkholt Thank you for the report. I will investigate the issue as soon as possible. Can you try with different file names and paths (or something that could help me to track down the bug)?

**Comment by jllodra** [comment]
@arkholt That bug is fixed in the new version (2.2.1), you can find it on the Releases page. There's a new load/save playlist feature too. Thank you!
